local ProtocolsFunc = {
	PlayerInfo.Send_Bag_Exchange_Pos,
	PlayerInfo.Send_Bag_Item_User,
	PlayerInfo.Send_Bag_Item_Sell,
	PlayerInfo.Send_Bag_Item_Sort,
	PlayerInfo.Send_Finish_Now_Guide,
	PlayerInfo.Send_Get_Cultivation_Info,
	PlayerInfo.Send_Get_Cultivation_Rivals_Info,
	PlayerInfo.Send_Get_Cultivation_Reward,
	PlayerInfo.Send_Refresh_Cultivation_Rivals,
	PlayerInfo.Send_Plunder_Cultivation_Rival,
	PlayerInfo.Send_Revenge_Cultivation_Rival,
	PlayerInfo.Send_Buy_Cultivation_Left_Plunder_Count,
	PlayerInfo.Send_Get_Login_Activity_Reward,
	PlayerInfo.Send_Smelting_Equip,
	PlayerInfo.Send_Social_Buy_Revenge_Times,
	PlayerInfo.Send_Social_Remove_Enemy,
	PlayerInfo.Send_Get_Player_Overview,
	PlayerInfo.Send_Send_Faction_Invite,
	PlayerInfo.Send_Buy_Vipgift,
	PlayerInfo.Send_Activity_Opt_Buy_Dailygift,
	PlayerInfo.Send_Activity_Opt_Get_Rank_Process_Reward,
	PlayerInfo.Send_Activity_Opt_Get_Rank_List,
	PlayerInfo.Send_Activity_Opt_Buy_Limitgift,
	PlayerInfo.Send_Welfare_Get_Recharge_Reward,
	PlayerInfo.Send_Welfare_Get_Consume_Reward,
	PlayerInfo.Send_Welfare_Get_Sevenday_Reward,
	PlayerInfo.Send_Talisman_Active,
	PlayerInfo.Send_Talisman_Lvup,
	PlayerInfo.Send_Wings_Active,
	PlayerInfo.Send_Wings_Bless,
	PlayerInfo.Send_Wings_Rankup,
	PlayerInfo.Send_Wings_Strength,
	PlayerInfo.Send_Equipdevelop_Operate,
	PlayerInfo.Send_Unlock_Title,
	PlayerInfo.Send_Rank_List_Query,
	PlayerInfo.Send_Query_Player_Info,
	PlayerInfo.Send_Chat_Whisper,
	PlayerInfo.Send_Sync_Mstime_App,
	PlayerInfo.Send_Mall_Buy,
	PlayerInfo.Send_Strength,
	PlayerInfo.Send_Create_Faction,
	PlayerInfo.Send_Faction_Join,
	PlayerInfo.Send_Raise_Base_Spell,
	PlayerInfo.Send_Upgrade_Anger_Spell,
	PlayerInfo.Send_Raise_Mount,
	PlayerInfo.Send_Upgrade_Mount,
	PlayerInfo.Send_Upgrade_Mount_One_Step,
	PlayerInfo.Send_Illusion_Mount_Active,
	PlayerInfo.Send_Illusion_Mount,
	PlayerInfo.Send_Gem,
	PlayerInfo.Send_Sweep_Vip_Instance,
	PlayerInfo.Send_Hang_Up,
	PlayerInfo.Send_Hang_Up_Setting,
	PlayerInfo.Send_Sweep_Trial_Instance,
	PlayerInfo.Send_Reset_Trial_Instance,
	PlayerInfo.Send_Social_Add_Friend,
	PlayerInfo.Send_Social_Sureadd_Friend,
	PlayerInfo.Send_Social_Gift_Friend,
	PlayerInfo.Send_Social_Recommend_Friend,
	PlayerInfo.Send_Social_Revenge_Enemy,
	PlayerInfo.Send_Social_Del_Friend,
	PlayerInfo.Send_Social_Clear_Apply,
	PlayerInfo.Send_Social_Add_Friend_Byname,
	PlayerInfo.Send_Chat_By_Channel,
	PlayerInfo.Send_Msg_Decline,
	PlayerInfo.Send_Block_Chat,
	PlayerInfo.Send_Faction_Getlist,
	PlayerInfo.Send_Faction_Manager,
	PlayerInfo.Send_Faction_Member_Operate,
	PlayerInfo.Send_Faction_Fast_Join,
	PlayerInfo.Send_Read_Mail,
	PlayerInfo.Send_Pick_Mail,
	PlayerInfo.Send_Pick_Mail_One_Step,
	PlayerInfo.Send_Remove_Mail_One_Step,
	PlayerInfo.Send_Cancel_Block_Chat,
	PlayerInfo.Send_World_Boss_Enroll,
	PlayerInfo.Send_Rank_Add_Like,
	PlayerInfo.Send_Res_Instance_Sweep,
	PlayerInfo.Send_Get_Activity_Reward,
	PlayerInfo.Send_Get_Achieve_Reward,
	PlayerInfo.Send_Get_Achieve_All_Reward,
	PlayerInfo.Send_Set_Title,
	PlayerInfo.Send_Init_Title,
	PlayerInfo.Send_Welfare_Shouchong_Reward,
	PlayerInfo.Send_Welfare_Checkin,
	PlayerInfo.Send_Welfare_Checkin_All,
	PlayerInfo.Send_Welfare_Checkin_Getback,
	PlayerInfo.Send_Welfare_Level,
	PlayerInfo.Send_Welfare_Active_Getback,
	PlayerInfo.Send_Welfare_Getalllist_Getback,
	PlayerInfo.Send_Welfare_Getall_Getback,
	PlayerInfo.Send_Pick_Quest_Reward,
	PlayerInfo.Send_Use_Virtual_Item,
	PlayerInfo.Send_Pick_Quest_Chapter_Reward,
	PlayerInfo.Send_Kuafu_3v3_Cancel_Match,
	PlayerInfo.Send_Kuafu_Xianfu_Match,
	PlayerInfo.Send_Buy_Xianfu_Item,
	PlayerInfo.Send_Doujiantai_Fight,
	PlayerInfo.Send_Doujiantai_Buytime,
	PlayerInfo.Send_Doujiantai_Clearcd,
	PlayerInfo.Send_Doujiantai_First_Reward,
	PlayerInfo.Send_Doujiantai_Get_Enemys_Info,
	PlayerInfo.Send_Doujiantai_Get_Rank,
	PlayerInfo.Send_Doujiantai_Refresh_Enemys,
	PlayerInfo.Send_Doujiantai_Top3,
	PlayerInfo.Send_Submit_Quest_Daily2,
	PlayerInfo.Send_Pick_Daily2_Quest_Reward,
	PlayerInfo.Send_Finish_Optional_Guide_Step,
	PlayerInfo.Send_Execute_Quest_Cmd_After_Accepted,
	PlayerInfo.Send_Storehouse_Hand_In,
	PlayerInfo.Send_Storehouse_Exchange,
	PlayerInfo.Send_Storehouse_Destroy,
	PlayerInfo.Send_Buy_Mass_Boss_Times,
	PlayerInfo.Send_Group_Instance_Match,
	PlayerInfo.Send_Buy_Group_Instance_Times,
	PlayerInfo.Send_Meridian_Practise,
	PlayerInfo.Send_Add_Meridian_Exp,
	PlayerInfo.Send_Raise_Mount_Level_Base,
	PlayerInfo.Send_Active_Mount,
	PlayerInfo.Send_Match_Single_Pvp,
	PlayerInfo.Send_Buy_Match_Single_Pvp_Times,
	PlayerInfo.Send_Pick_Match_Single_Pvp_Extra_Reward,
	PlayerInfo.Send_Active_Appearance,
	PlayerInfo.Send_Equip_Appearance,
	PlayerInfo.Send_Cancel_Equip_Appearance,
	PlayerInfo.Send_Draw_Lottery,
	PlayerInfo.Send_Rename,
	PlayerInfo.Send_Teleport,
	PlayerInfo.Send_Use_Gameobject,
	PlayerInfo.Send_Instance_Exit,
	PlayerInfo.Send_Ride_Mount,
	PlayerInfo.Send_Change_Battle_Mode,
	PlayerInfo.Send_Jump_Start,
	PlayerInfo.Send_Enter_Trial_Instance,
	PlayerInfo.Send_Teleport_Main_City,
	PlayerInfo.Send_Use_Broadcast_Gameobject,
	PlayerInfo.Send_World_Boss_Fight,
	PlayerInfo.Send_Res_Instance_Enter,
	PlayerInfo.Send_Teleport_Map,
	PlayerInfo.Send_Teleport_Field_Boss,
	PlayerInfo.Send_Talk_With_Npc,
	PlayerInfo.Send_Loot_Select,
	PlayerInfo.Send_Gold_Respawn,
	PlayerInfo.Send_Xianfu_Random_Respawn,
	PlayerInfo.Send_Clientsubscription,
	PlayerInfo.Send_Use_Jump_Point,
	PlayerInfo.Send_Back_To_Famity,
	PlayerInfo.Send_Pick_Offline_Reward,
	PlayerInfo.Send_Query_Mass_Boss_Info,
	PlayerInfo.Send_Query_Mass_Boss_Rank,
	PlayerInfo.Send_Enter_Risk_Instance,
}
local FuncName = {
	"Send_Bag_Exchange_Pos",
	"Send_Bag_Item_User",
	"Send_Bag_Item_Sell",
	"Send_Bag_Item_Sort",
	"Send_Finish_Now_Guide",
	"Send_Get_Cultivation_Info",
	"Send_Get_Cultivation_Rivals_Info",
	"Send_Get_Cultivation_Reward",
	"Send_Refresh_Cultivation_Rivals",
	"Send_Plunder_Cultivation_Rival",
	"Send_Revenge_Cultivation_Rival",
	"Send_Buy_Cultivation_Left_Plunder_Count",
	"Send_Get_Login_Activity_Reward",
	"Send_Smelting_Equip",
	"Send_Social_Buy_Revenge_Times",
	"Send_Social_Remove_Enemy",
	"Send_Get_Player_Overview",
	"Send_Send_Faction_Invite",
	"Send_Buy_Vipgift",
	"Send_Activity_Opt_Buy_Dailygift",
	"Send_Activity_Opt_Get_Rank_Process_Reward",
	"Send_Activity_Opt_Get_Rank_List",
	"Send_Activity_Opt_Buy_Limitgift",
	"Send_Welfare_Get_Recharge_Reward",
	"Send_Welfare_Get_Consume_Reward",
	"Send_Welfare_Get_Sevenday_Reward",
	"Send_Talisman_Active",
	"Send_Talisman_Lvup",
	"Send_Wings_Active",
	"Send_Wings_Bless",
	"Send_Wings_Rankup",
	"Send_Wings_Strength",
	"Send_Equipdevelop_Operate",
	"Send_Unlock_Title",
	"Send_Rank_List_Query",
	"Send_Query_Player_Info",
	"Send_Chat_Whisper",
	"Send_Sync_Mstime_App",
	"Send_Mall_Buy",
	"Send_Strength",
	"Send_Create_Faction",
	"Send_Faction_Join",
	"Send_Raise_Base_Spell",
	"Send_Upgrade_Anger_Spell",
	"Send_Raise_Mount",
	"Send_Upgrade_Mount",
	"Send_Upgrade_Mount_One_Step",
	"Send_Illusion_Mount_Active",
	"Send_Illusion_Mount",
	"Send_Gem",
	"Send_Sweep_Vip_Instance",
	"Send_Hang_Up",
	"Send_Hang_Up_Setting",
	"Send_Sweep_Trial_Instance",
	"Send_Reset_Trial_Instance",
	"Send_Social_Add_Friend",
	"Send_Social_Sureadd_Friend",
	"Send_Social_Gift_Friend",
	"Send_Social_Recommend_Friend",
	"Send_Social_Revenge_Enemy",
	"Send_Social_Del_Friend",
	"Send_Social_Clear_Apply",
	"Send_Social_Add_Friend_Byname",
	"Send_Chat_By_Channel",
	"Send_Msg_Decline",
	"Send_Block_Chat",
	"Send_Faction_Getlist",
	"Send_Faction_Manager",
	"Send_Faction_Member_Operate",
	"Send_Faction_Fast_Join",
	"Send_Read_Mail",
	"Send_Pick_Mail",
	"Send_Pick_Mail_One_Step",
	"Send_Remove_Mail_One_Step",
	"Send_Cancel_Block_Chat",
	"Send_World_Boss_Enroll",
	"Send_Rank_Add_Like",
	"Send_Res_Instance_Sweep",
	"Send_Get_Activity_Reward",
	"Send_Get_Achieve_Reward",
	"Send_Get_Achieve_All_Reward",
	"Send_Set_Title",
	"Send_Init_Title",
	"Send_Welfare_Shouchong_Reward",
	"Send_Welfare_Checkin",
	"Send_Welfare_Checkin_All",
	"Send_Welfare_Checkin_Getback",
	"Send_Welfare_Level",
	"Send_Welfare_Active_Getback",
	"Send_Welfare_Getalllist_Getback",
	"Send_Welfare_Getall_Getback",
	"Send_Pick_Quest_Reward",
	"Send_Use_Virtual_Item",
	"Send_Pick_Quest_Chapter_Reward",
	"Send_Kuafu_3v3_Cancel_Match",
	"Send_Kuafu_Xianfu_Match",
	"Send_Buy_Xianfu_Item",
	"Send_Doujiantai_Fight",
	"Send_Doujiantai_Buytime",
	"Send_Doujiantai_Clearcd",
	"Send_Doujiantai_First_Reward",
	"Send_Doujiantai_Get_Enemys_Info",
	"Send_Doujiantai_Get_Rank",
	"Send_Doujiantai_Refresh_Enemys",
	"Send_Doujiantai_Top3",
	"Send_Submit_Quest_Daily2",
	"Send_Pick_Daily2_Quest_Reward",
	"Send_Finish_Optional_Guide_Step",
	"Send_Execute_Quest_Cmd_After_Accepted",
	"Send_Storehouse_Hand_In",
	"Send_Storehouse_Exchange",
	"Send_Storehouse_Destroy",
	"Send_Buy_Mass_Boss_Times",
	"Send_Group_Instance_Match",
	"Send_Buy_Group_Instance_Times",
	"Send_Meridian_Practise",
	"Send_Add_Meridian_Exp",
	"Send_Raise_Mount_Level_Base",
	"Send_Active_Mount",
	"Send_Match_Single_Pvp",
	"Send_Buy_Match_Single_Pvp_Times",
	"Send_Pick_Match_Single_Pvp_Extra_Reward",
	"Send_Active_Appearance",
	"Send_Equip_Appearance",
	"Send_Cancel_Equip_Appearance",
	"Send_Draw_Lottery",
	"Send_Rename",
	"Send_Teleport",
	"Send_Use_Gameobject",
	"Send_Instance_Exit",
	"Send_Ride_Mount",
	"Send_Change_Battle_Mode",
	"Send_Jump_Start",
	"Send_Enter_Trial_Instance",
	"Send_Teleport_Main_City",
	"Send_Use_Broadcast_Gameobject",
	"Send_World_Boss_Fight",
	"Send_Res_Instance_Enter",
	"Send_Teleport_Map",
	"Send_Teleport_Field_Boss",
	"Send_Talk_With_Npc",
	"Send_Loot_Select",
	"Send_Gold_Respawn",
	"Send_Xianfu_Random_Respawn",
	"Send_Clientsubscription",
	"Send_Use_Jump_Point",
	"Send_Back_To_Famity",
	"Send_Pick_Offline_Reward",
	"Send_Query_Mass_Boss_Info",
	"Send_Query_Mass_Boss_Rank",
	"Send_Enter_Risk_Instance",
}


function PlayerInfo:SendProtocol()
	
	-- 先发送升级命令 升到31级
	--local cmd = "@Rank 50"
	--self:call_chat_by_channel(CHAT_TYPE_WORLD, cmd)
	--[[local indice = GetRandomIndexTable(#ProtocolsFunc, math.min(#ProtocolsFunc, 6))
	for _, index in ipairs(indice) do
		local callback = ProtocolsFunc[index]
		--outFmtDebug("%s invoke %s", self:GetGuid(), FuncName[index])
		doxpcall(callback, self)
	end--]]
	
	
	return true
	
end

function PlayerInfo:SendRobotRank()
		-- 先发送升级命令 升到31级
	--local cmd = "@Rank 200"
	--local cmd = "@选择主线 10250"
	--self:call_chat_by_channel(CHAT_TYPE_WORLD, cmd)
	--local cmd = "@制造 30000 1"
	--self:call_chat_by_channel(CHAT_TYPE_WORLD, cmd)

	--local cmd = "@制造 30001 1"
	--self:call_chat_by_channel(CHAT_TYPE_WORLD, cmd)

	--local cmd = "@制造 30002 1"
	--self:call_chat_by_channel(CHAT_TYPE_WORLD, cmd)

	self:call_one_step_robot_up(randInt(1,3))
	return true
	
	--[[local cmd = "@随机装备 30 1"
	self:call_chat_by_channel(CHAT_TYPE_WORLD, cmd)
	return true--]]
end

function PlayerInfo:SendRobotAppearance()
	local cmd = "@SUPER_ROBOT"
	self:call_chat_by_channel(CHAT_TYPE_WORLD, cmd)
	return false
end

function PlayerInfo:SendRide()
	self:call_ride_mount()
	return false
end

